name: PR Review Author Notification Workflow

on:
  pull_request_review:
    types:
      - submitted

jobs:
  check_review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      statuses: write
    steps:
      - name: Check PR Review
        id: check_review
        uses: actions/github-script@v6
        with:
          result-encoding: string
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const review = context.payload.review;
            const isMaintainer = review.user.type === "User" && 
            review.user.login === "${{ github.repository_owner }}"; 
            const isApproval = review.state === "approved";
            const isRequestForChanges = review.state === "changes_requested";

            if (!isMaintainer) {
              console.log('Reviewer is not a maintainer.');
              return 'not_maintainer'; 
            }

            if (isApproval) {
              console.log("Maintainer approved the PR.");
              return "approved";
            } else if (isRequestForChanges) {
              console.log("Maintainer requested changes on the PR.");
              return "changes_requested";
            }

            console.log("Review action does not match criteria.");
            return "not_triggered";
            
        env:
          MAINTAINER_USERNAME: ${{ github.repository_owner }}
      - name: Comment if changes were requested
        if: steps.check_review.outputs.result == 'changes_requested'
        uses: winterjung/comment@v1.1.0
        with:
          type: create
          issue_number: ${{ github.event.pull_request.number }}
          token: ${{ github.token }}
          body: |
            Hi, @${{ github.event.pull_request.user.login }}! One or more reviewers have requested changes. 👨‍💻
            Please address them. I'll be back once they approve or I see new commits. Have a nice day! ✨
      - name: Comment if changes were approved
        uses: winterjung/comment@v1.1.0
        if: steps.check_review.outputs.result == 'approved'
        with:
          type: create
          issue_number: ${{ github.event.pull_request.number }}
          token: ${{ github.token }}
          body: |
            Hi, @${{ github.event.pull_request.user.login }}! I'm happy to inform you your pull
            request was approved by a maintainer! ✅


